
import React, { useState, useMemo, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ClipboardList, Clock, ShieldCheck, ChevronRight, Filter, Search, X, FileText, TrendingUp, AlertCircle, Download, Sparkles, Award } from 'lucide-react';
import { Exam } from '../../types';

const Exams: React.FC = () => {
  const [selectedAnalysis, setSelectedAnalysis] = useState<any>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [submittedIds, setSubmittedIds] = useState<string[]>([]);

  useEffect(() => {
    const saved = JSON.parse(localStorage.getItem('submitted_exams') || '[]');
    setSubmittedIds(saved);
  }, []);

  const exams: Exam[] = [
    {
      id: 'ex-101',
      title: 'Operating Systems Mid-Term',
      subject: 'Institutional • CSE-402',
      date: 'Oct 15, 2024 • 10:00 AM',
      duration: 60,
      mode: 1,
      strictness: 'High',
      status: submittedIds.includes('ex-101') ? 'SUBMITTED' : 'NOT_STARTED'
    },
    {
      id: 'ex-102',
      title: 'Calculus Quiz 2',
      subject: 'Institutional • MAT-201',
      date: 'Oct 12, 2024 • 02:00 PM',
      duration: 30,
      mode: 2,
      strictness: 'Moderate',
      status: submittedIds.includes('ex-102') ? 'SUBMITTED' : 'SUBMITTED' // Calculus quiz hardcoded as submitted per mock data
    },
    {
      id: 'ex-ai-01',
      title: 'React Fundamentals Final',
      subject: 'Personal Learning Path',
      date: 'Oct 08, 2024 • 04:00 PM',
      duration: 45,
      mode: 1,
      strictness: 'Moderate',
      status: 'RESULT_PUBLISHED'
    }
  ];

  const filteredExams = useMemo(() => {
    return exams.filter(e => 
      e.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
      e.subject.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [searchQuery, exams]);

  const mockAnalysis = {
    'ex-ai-01': {
      id: 'AN-29384',
      title: 'React Fundamentals Final',
      score: 82,
      total: 100,
      integrity: 98,
      feedback: "Strong grasp of component lifecycle, but minor errors in state management with hooks.",
      mistakes: [
        { q: "Explain the reconciliation algorithm.", note: "Incomplete explanation of 'diffing' process." },
        { q: "Difference between UseEffect and UseLayoutEffect.", note: "Confused the execution timing of both hooks." }
      ],
      weakTopics: ["Hooks Lifecycle", "Diffing Algorithm"],
      planUpdate: "Review 'Advanced Hooks' in Module 3."
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'SUBMITTED': return 'bg-green-100 text-green-700';
      case 'RESULT_PUBLISHED': return 'bg-indigo-100 text-indigo-700';
      case 'DISQUALIFIED': return 'bg-red-100 text-red-700';
      case 'IN_PROGRESS': return 'bg-blue-100 text-blue-700';
      default: return 'bg-gray-100 text-gray-700';
    }
  };

  const handleViewAnalysis = (id: string) => {
    const analysis = mockAnalysis[id as keyof typeof mockAnalysis] || {
      id: 'AN-99999',
      title: 'General Assessment',
      score: 75,
      total: 100,
      integrity: 95,
      feedback: "Good attempt. Practice more diagrams.",
      mistakes: [{ q: "General Question", note: "Need more depth in reasoning." }],
      weakTopics: ["Logical Reasoning"],
      planUpdate: "Focus on Module 2 exercises."
    };
    setSelectedAnalysis(analysis);
  };

  const downloadReport = () => {
    if (!selectedAnalysis) return;
    const content = `
EDUADAPTIVE AI - OFFICIAL PERFORMANCE REPORT
---------------------------------------------
REPORT ID: ${selectedAnalysis.id}
EXAM: ${selectedAnalysis.title}
DATE: ${new Date().toLocaleDateString()}

FINAL SCORE: ${selectedAnalysis.score}/${selectedAnalysis.total}
INTEGRITY SCORE: ${selectedAnalysis.integrity}%
PROFICIENCY: ${selectedAnalysis.score > 80 ? 'EXCELLENT' : 'GOOD'}

Mistakes Identified:
${selectedAnalysis.mistakes?.map((m:any) => `- Q: ${m.q}\n  Note: ${m.note}`).join('\n')}

Weak Topics for Revision:
${selectedAnalysis.weakTopics?.map((t:string) => `- ${t}`).join('\n')}

Adaptive Feedback:
${selectedAnalysis.feedback}
---------------------------------------------
Generated by EduAdaptive AI Engine v4.0
    `;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Exam_Report_${selectedAnalysis.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-10">
      <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div>
          <h1 className="text-4xl font-black text-gray-900">Exam Center</h1>
          <p className="text-gray-500 font-medium">Consolidated view of academic and personal assessments.</p>
        </div>
        <div className="flex gap-4 w-full md:w-auto">
          <div className="relative flex-1 md:w-64">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
            <input 
              type="text" 
              placeholder="Search exams..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-12 pr-4 py-3.5 bg-white border border-gray-100 rounded-2xl outline-none focus:ring-4 focus:ring-indigo-100 transition-all font-bold"
            />
          </div>
        </div>
      </header>

      {/* Analysis Modal */}
      {selectedAnalysis && (
        <div className="fixed inset-0 z-[100] bg-black/70 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-white w-full max-w-4xl max-h-[90vh] rounded-[50px] shadow-3xl overflow-hidden flex flex-col animate-in zoom-in-95 duration-300">
            <div className="p-8 md:p-12 border-b border-gray-100 flex justify-between items-center bg-indigo-900 text-white">
              <div className="flex items-center gap-4">
                <FileText size={40} className="text-indigo-300" />
                <div>
                  <h2 className="text-3xl font-black">{selectedAnalysis.title} Report</h2>
                  <p className="text-indigo-200 font-bold uppercase tracking-widest text-[10px]">Reference ID: {selectedAnalysis.id}</p>
                </div>
              </div>
              <button onClick={() => setSelectedAnalysis(null)} className="p-2 hover:bg-white/10 rounded-full transition-colors">
                <X size={32} />
              </button>
            </div>
            
            <div className="flex-1 overflow-y-auto p-10 space-y-12 no-scrollbar">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="p-8 bg-indigo-50 rounded-[40px] text-center space-y-2 border border-indigo-100 shadow-inner group">
                  <p className="text-[10px] font-black text-indigo-400 uppercase tracking-[0.2em]">Final Score</p>
                  <p className="text-6xl font-black text-indigo-900">{selectedAnalysis.score}/{selectedAnalysis.total}</p>
                </div>
                <div className="p-8 bg-green-50 rounded-[40px] text-center space-y-2 border border-green-100 shadow-inner group">
                  <p className="text-[10px] font-black text-green-400 uppercase tracking-[0.2em]">Integrity Score</p>
                  <p className="text-6xl font-black text-green-900">{selectedAnalysis.integrity}%</p>
                </div>
                <div className="p-8 bg-orange-50 rounded-[40px] text-center space-y-2 border border-orange-100 shadow-inner group">
                  <p className="text-[10px] font-black text-orange-400 uppercase tracking-[0.2em]">Rank Percentile</p>
                  <p className="text-6xl font-black text-orange-900">Top 8%</p>
                </div>
              </div>

              <div className="space-y-6">
                <h3 className="text-2xl font-black flex items-center gap-3">
                  <AlertCircle className="text-red-500" /> Granular Error Tracking
                </h3>
                <div className="space-y-4">
                  {selectedAnalysis.mistakes?.map((m: any, idx: number) => (
                    <div key={idx} className="p-8 bg-gray-50 rounded-[35px] border border-gray-100 flex gap-6 items-start">
                      <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center font-black text-indigo-600 shadow-sm shrink-0">0{idx+1}</div>
                      <div>
                        <p className="font-black text-gray-900 text-lg mb-2">Q: {m.q}</p>
                        <p className="text-sm text-red-600 font-bold leading-relaxed">System Note: {m.note}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                <div className="space-y-6">
                  <h3 className="text-2xl font-black flex items-center gap-3">
                    <TrendingUp className="text-indigo-600" /> Proficiency Gaps
                  </h3>
                  <div className="flex flex-wrap gap-3">
                    {selectedAnalysis.weakTopics?.map((t: string) => (
                      <span key={t} className="px-6 py-3 bg-white text-indigo-700 rounded-full font-black text-xs border border-indigo-100 shadow-sm">{t}</span>
                    ))}
                  </div>
                </div>
                <div className="space-y-6">
                  <h3 className="text-2xl font-black flex items-center gap-3 text-green-600">
                    <Award /> Adaptive Growth Step
                  </h3>
                  <div className="p-8 bg-green-50 border border-green-100 rounded-[40px] text-green-800 font-bold leading-relaxed text-lg shadow-inner">
                    {selectedAnalysis.planUpdate}
                  </div>
                </div>
              </div>
            </div>

            <div className="p-8 bg-gray-50 border-t border-gray-100 flex flex-col md:flex-row justify-between items-center gap-4">
               <p className="text-xs text-gray-400 font-black uppercase tracking-widest italic">Authenticity Verified: EduAdaptive Blockchain v4.2</p>
               <button 
                onClick={downloadReport}
                className="flex items-center gap-3 px-10 py-5 bg-indigo-600 text-white rounded-[30px] font-black hover:bg-indigo-700 transition-all shadow-3xl shadow-indigo-100 hover:-translate-y-1"
               >
                 <Download size={24} /> Download PDF Report
               </button>
            </div>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 gap-6">
        {filteredExams?.map((exam) => (
          <div key={exam.id} className="bg-white p-6 md:p-10 rounded-[45px] border border-gray-100 shadow-sm flex flex-col md:flex-row justify-between items-center group hover:shadow-2xl transition-all duration-500">
            <div className="flex items-center gap-8 w-full">
              <div className="w-20 h-20 bg-indigo-50 text-indigo-600 rounded-[30px] flex items-center justify-center shrink-0 group-hover:bg-indigo-600 group-hover:text-white transition-all duration-500">
                <ClipboardList size={36} />
              </div>
              <div className="flex-1 space-y-2">
                <div className="flex flex-wrap items-center gap-3">
                  <h3 className="text-2xl font-black text-gray-900 group-hover:text-indigo-600 transition-colors">{exam.title}</h3>
                  <span className={`px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest ${getStatusColor(exam.status)}`}>
                    {exam.status.replace('_', ' ')}
                  </span>
                </div>
                <p className="text-gray-400 font-bold uppercase tracking-widest text-[10px]">{exam.subject}</p>
                <div className="flex flex-wrap gap-6 text-sm font-bold text-gray-400 pt-2">
                  <span className="flex items-center gap-2"><Clock size={18} className="text-indigo-400"/> {exam.duration} mins</span>
                  <span className="flex items-center gap-2"><ShieldCheck size={18} className="text-indigo-400"/> Mode {exam.mode} ({exam.strictness})</span>
                  <span className="flex items-center gap-2"><ChevronRight size={18} className="text-indigo-400"/> {exam.date}</span>
                </div>
              </div>
            </div>

            <div className="mt-8 md:mt-0 w-full md:w-auto">
              {exam.status === 'NOT_STARTED' ? (
                <Link 
                  to={`/student/exam/${exam.id}/details`}
                  className="w-full md:w-auto flex items-center justify-center gap-3 px-10 py-5 bg-indigo-600 text-white rounded-[24px] font-black hover:bg-indigo-700 transition-all shadow-3xl shadow-indigo-100 hover:-translate-y-1"
                >
                  Enter Exam Room <ChevronRight size={20} />
                </Link>
              ) : exam.status === 'RESULT_PUBLISHED' ? (
                <button 
                  onClick={() => handleViewAnalysis(exam.id)}
                  className="w-full md:w-auto flex items-center justify-center gap-3 px-10 py-5 bg-white border-2 border-indigo-600 text-indigo-600 rounded-[24px] font-black hover:bg-indigo-50 transition-all"
                >
                  View Analysis
                </button>
              ) : (
                <button disabled className="w-full md:w-auto px-10 py-5 bg-gray-100 text-gray-400 rounded-[24px] font-black cursor-not-allowed uppercase tracking-widest text-xs">
                  Submitted
                </button>
              )}
            </div>
          </div>
        ))}
        {filteredExams?.length === 0 && (
          <div className="text-center py-20 bg-white rounded-[40px] border-2 border-dashed border-gray-100">
             <ClipboardList size={64} className="mx-auto text-gray-200 mb-4" />
             <p className="text-xl font-black text-gray-400 uppercase">No Matching Exams Found</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default Exams;
